/**
 * IMAGINE Photo Organizer - DOM Elements & Validation
 * Pure Vanilla JavaScript (Offline-ready, no dependencies)
 */

export const dom = {
  mediaGrid: document.getElementById('mediaGrid'),
  emptyState: document.getElementById('emptyState'),
  emptyImportBtn: document.getElementById('emptyImportBtn'),
  gridScrollContainer: document.getElementById('gridScrollContainer'),
  zoomSlider: document.getElementById('zoomSlider'),
  langSelect: document.getElementById('langSelect'),
  searchInput: document.getElementById('searchInput'),
  clearSearchBtn: document.getElementById('clearSearchBtn'),
  refreshBtn: document.getElementById('refreshBtn'),
  importBtn: document.getElementById('importBtn'),
  viewTabs: document.getElementById('viewTabs'),
  viewGridBtn: document.getElementById('viewGridBtn'),
  viewMapBtn: document.getElementById('viewMapBtn'),
  mapViewContainer: document.getElementById('mapViewContainer'),
  leafletMap: document.getElementById('leafletMap'),
  mapSearchOverlay: document.getElementById('mapSearchOverlay'),
  mapSearchBox: document.querySelector('.map-search-box'),
  mapSearchIcon: document.getElementById('mapSearchIcon'),
  mapSearchInput: document.getElementById('mapSearchInput'),
  clearMapSearchBtn: document.getElementById('clearMapSearchBtn'),
  mapSearchSpinner: document.getElementById('mapSearchSpinner'),
  mapSearchResults: document.getElementById('mapSearchResults'),
  mapPhotoCount: document.getElementById('mapPhotoCount'),
  mapFitBoundsBtn: document.getElementById('mapFitBoundsBtn'),
  mapToggleUnmappedBtn: document.getElementById('mapToggleUnmappedBtn'),
  mapLoadMoreBtn: document.getElementById('mapLoadMoreBtn'),
  mapLoadAllBtn: document.getElementById('mapLoadAllBtn'),
  unmappedBtnLabel: document.getElementById('unmappedBtnLabel'),
  unmappedTray: document.getElementById('unmappedTray'),
  unmappedTrayTitle: document.getElementById('unmappedTrayTitle'),
  unmappedSelectedCount: document.getElementById('unmappedSelectedCount'),
  unmappedSelectAllBtn: document.getElementById('unmappedSelectAllBtn'),
  unmappedDeselectAllBtn: document.getElementById('unmappedDeselectAllBtn'),
  unmappedLoadMoreBtn: document.getElementById('unmappedLoadMoreBtn'),
  closeUnmappedTrayBtn: document.getElementById('closeUnmappedTrayBtn'),
  unmappedPhotosList: document.getElementById('unmappedPhotosList'),
  unmappedPhotoTooltip: document.getElementById('unmappedPhotoTooltip'),
  unmappedTooltipImg: document.getElementById('unmappedTooltipImg'),
  unmappedTooltipTitle: document.getElementById('unmappedTooltipTitle'),
  unmappedTooltipMeta: document.getElementById('unmappedTooltipMeta'),
  sortSelect: document.getElementById('sortSelect'),
  contentToolbar: document.getElementById('contentToolbar'),
  categoryToolbar: document.getElementById('categoryToolbar'),
  filterIndicator: document.getElementById('filterIndicator'),
  categoryBackBtn: document.getElementById('categoryBackBtn'),
  categoryBackBtnLabel: document.getElementById('categoryBackBtnLabel'),
  filterLabel: document.getElementById('filterLabel'),
  clearFiltersBtn: document.getElementById('clearFiltersBtn'),
  categoryViewContainer: document.getElementById('categoryViewContainer'),
  categoryCardsGrid: document.getElementById('categoryCardsGrid'),
  categoryViewTitle: document.getElementById('categoryViewTitle'),
  categoryViewSubtitle: document.getElementById('categoryViewSubtitle'),
  categorySortSelect: document.getElementById('categorySortSelect'),
  categoryAddBtn: document.getElementById('categoryAddBtn'),
  categoryAddBtnLabel: document.getElementById('categoryAddBtnLabel'),
  categoryEmptyState: document.getElementById('categoryEmptyState'),
  categoryEmptyIcon: document.getElementById('categoryEmptyIcon'),
  categoryEmptyTitle: document.getElementById('categoryEmptyTitle'),
  categoryEmptyText: document.getElementById('categoryEmptyText'),
  categoryEmptyActionBtn: document.getElementById('categoryEmptyActionBtn'),
  totalMediaCount: document.getElementById('totalMediaCount'),
  totalPhotosCount: document.getElementById('totalPhotosCount'),
  totalVideosCount: document.getElementById('totalVideosCount'),
  totalAudioCount: document.getElementById('totalAudioCount'),
  totalPicksCount: document.getElementById('totalPicksCount'),
  totalRejectsCount: document.getElementById('totalRejectsCount'),
  totalNotRejectsCount: document.getElementById('totalNotRejectsCount'),
  totalUnratedCount: document.getElementById('totalUnratedCount'),
  navAllMedia: document.getElementById('navAllMedia'),
  navPhotos: document.getElementById('navPhotos'),
  navVideos: document.getElementById('navVideos'),
  navAudio: document.getElementById('navAudio'),
  navPicks: document.getElementById('navPicks'),
  navRejects: document.getElementById('navRejects'),
  navNotRejects: document.getElementById('navNotRejects'),
  navUnrated: document.getElementById('navUnrated'),
  albumsList: document.getElementById('albumsList'),
  newAlbumBtn: document.getElementById('newAlbumBtn'),
  newTagBtn: document.getElementById('newTagBtn'),
  foldersTree: document.getElementById('foldersTree'),
  tagCategoryPeople: document.getElementById('tagCategoryPeople'),
  tagCategoryPlaces: document.getElementById('tagCategoryPlaces'),
  tagCategoryEvents: document.getElementById('tagCategoryEvents'),
  tagCategoryKeyword: document.getElementById('tagCategoryKeyword'),
  batchActionBar: document.getElementById('batchActionBar'),
  batchSelectedCount: document.getElementById('batchSelectedCount'),
  batchRating: document.getElementById('batchRating'),
  batchPickBtn: document.getElementById('batchPickBtn'),
  batchRejectBtn: document.getElementById('batchRejectBtn'),
  batchDeleteBtn: document.getElementById('batchDeleteBtn'),
  batchAddTagBtn: document.getElementById('batchAddTagBtn'),
  batchAddAlbumBtn: document.getElementById('batchAddAlbumBtn'),
  batchDateBtn: document.getElementById('batchDateBtn'),
  batchMoveBtn: document.getElementById('batchMoveBtn'),
  batchClearBtn: document.getElementById('batchClearBtn'),
  timelineContainer: document.getElementById('timelineContainer'),
  resetTimelineBtn: document.getElementById('resetTimelineBtn'),
  rightInspector: document.getElementById('rightInspector'),
  inspectorResizerLeft: document.getElementById('inspectorResizerLeft'),
  toggleInspectorBtn: document.getElementById('toggleInspectorBtn'),
  closeInspectorBtn: document.getElementById('closeInspectorBtn'),
  inspectorNoSelection: document.getElementById('inspectorNoSelection'),
  inspectorSelection: document.getElementById('inspectorSelection'),
  inspectorImg: document.getElementById('inspectorImg'),
  openLoupeFromInspector: document.getElementById('openLoupeFromInspector'),
  inspectorAddToAlbumBtn: document.getElementById('inspectorAddToAlbumBtn'),
  inspectorMoveBtn: document.getElementById('inspectorMoveBtn'),
  inspectorDeleteBtn: document.getElementById('inspectorDeleteBtn'),
  inspectorRating: document.getElementById('inspectorRating'),
  inspectorFlag: document.getElementById('inspectorFlag'),
  fileInfoSection: document.getElementById('fileInfoSection'),
  fileInfoBody: document.getElementById('fileInfoBody'),
  fileInfoResizer: document.getElementById('fileInfoResizer'),
  infoFileName: document.getElementById('infoFileName'),
  infoFileNameRow: document.getElementById('infoFileNameRow'),
  renameFileBtn: document.getElementById('renameFileBtn'),
  renameFileForm: document.getElementById('renameFileForm'),
  renameFileInput: document.getElementById('renameFileInput'),
  saveRenameBtn: document.getElementById('saveRenameBtn'),
  cancelRenameBtn: document.getElementById('cancelRenameBtn'),
  infoMediaType: document.getElementById('infoMediaType'),
  infoDimensions: document.getElementById('infoDimensions'),
  infoFileSize: document.getElementById('infoFileSize'),
  infoDateTaken: document.getElementById('infoDateTaken'),
  infoDateTakenRow: document.getElementById('infoDateTakenRow'),
  editDateTakenBtn: document.getElementById('editDateTakenBtn'),
  editDateTakenForm: document.getElementById('editDateTakenForm'),
  editDateTakenInput: document.getElementById('editDateTakenInput'),
  saveDateTakenBtn: document.getElementById('saveDateTakenBtn'),
  cancelDateTakenBtn: document.getElementById('cancelDateTakenBtn'),
  infoCaption: document.getElementById('infoCaption'),
  infoCaptionRow: document.getElementById('infoCaptionRow'),
  editCaptionBtn: document.getElementById('editCaptionBtn'),
  editCaptionForm: document.getElementById('editCaptionForm'),
  editCaptionInput: document.getElementById('editCaptionInput'),
  saveCaptionBtn: document.getElementById('saveCaptionBtn'),
  cancelCaptionBtn: document.getElementById('cancelCaptionBtn'),
  infoFilePath: document.getElementById('infoFilePath'),
  infoFilePathRow: document.getElementById('infoFilePathRow'),
  inspectorMovePathBtn: document.getElementById('inspectorMovePathBtn'),
  avSection: document.getElementById('avSection'),
  avBody: document.getElementById('avBody'),
  avResizer: document.getElementById('avResizer'),
  infoDuration: document.getElementById('infoDuration'),
  infoArtist: document.getElementById('infoArtist'),
  infoTitle: document.getElementById('infoTitle'),
  infoAlbum: document.getElementById('infoAlbum'),
  infoGenre: document.getElementById('infoGenre'),
  infoCodec: document.getElementById('infoCodec'),
  infoBitrate: document.getElementById('infoBitrate'),
  infoAudioDetails: document.getElementById('infoAudioDetails'),
  exifSection: document.getElementById('exifSection'),
  exifBody: document.getElementById('exifBody'),
  exifResizer: document.getElementById('exifResizer'),
  infoCamera: document.getElementById('infoCamera'),
  infoLens: document.getElementById('infoLens'),
  infoExposure: document.getElementById('infoExposure'),
  infoAperture: document.getElementById('infoAperture'),
  infoIso: document.getElementById('infoIso'),
  infoFocal: document.getElementById('infoFocal'),
  infoGps: document.getElementById('infoGps'),
  inspectorGpsActions: document.getElementById('inspectorGpsActions'),
  inspectorShowOnMapBtn: document.getElementById('inspectorShowOnMapBtn'),
  inspectorClearGpsBtn: document.getElementById('inspectorClearGpsBtn'),
  inspectorPlaceOnMapBtn: document.getElementById('inspectorPlaceOnMapBtn'),
  inspectorMiniMap: document.getElementById('inspectorMiniMap'),
  inspectorTags: document.getElementById('inspectorTags'),
  addTagInput: document.getElementById('addTagInput'),
  addTagCategorySelect: document.getElementById('addTagCategorySelect'),
  tagSuggestions: document.getElementById('tagSuggestions'),
  addTagBtn: document.getElementById('addTagBtn'),
  loupeModal: document.getElementById('loupeModal'),
  loupeBackdrop: document.getElementById('loupeBackdrop'),
  loupeImageViewport: document.getElementById('loupeImageViewport'),
  loupeImg: document.getElementById('loupeImg'),
  loupeVideo: document.getElementById('loupeVideo'),
  loupeAudioContainer: document.getElementById('loupeAudioContainer'),
  loupeAudioCover: document.getElementById('loupeAudioCover'),
  loupeAudioTitle: document.getElementById('loupeAudioTitle'),
  loupeAudioArtist: document.getElementById('loupeAudioArtist'),
  loupeAudio: document.getElementById('loupeAudio'),
  loupeFileName: document.getElementById('loupeFileName'),
  loupeIndex: document.getElementById('loupeIndex'),
  loupeRating: document.getElementById('loupeRating'),
  loupeFlag: document.getElementById('loupeFlag'),
  loupeZoomControls: document.getElementById('loupeZoomControls'),
  loupeZoomOutBtn: document.getElementById('loupeZoomOutBtn'),
  loupeZoomInBtn: document.getElementById('loupeZoomInBtn'),
  loupeZoomResetBtn: document.getElementById('loupeZoomResetBtn'),
  loupeZoomSlider: document.getElementById('loupeZoomSlider'),
  loupePrevBtn: document.getElementById('loupePrevBtn'),
  loupeNextBtn: document.getElementById('loupeNextBtn'),
  loupeCloseBtn: document.getElementById('loupeCloseBtn'),
  loupeDeleteBtn: document.getElementById('loupeDeleteBtn'),
  loupeQuickEditBtn: document.getElementById('loupeQuickEditBtn'),
  quickEditToolbar: document.getElementById('quickEditToolbar'),
  quickEditContainer: document.getElementById('quickEditContainer'),
  quickEditCanvas: document.getElementById('quickEditCanvas'),
  cropOverlay: document.getElementById('cropOverlay'),
  cropBox: document.getElementById('cropBox'),
  cropScrimTop: document.getElementById('cropScrimTop'),
  cropScrimBottom: document.getElementById('cropScrimBottom'),
  cropScrimLeft: document.getElementById('cropScrimLeft'),
  cropScrimRight: document.getElementById('cropScrimRight'),
  cropDimensionsBadge: document.getElementById('cropDimensionsBadge'),
  cropAspectRatioSelect: document.getElementById('cropAspectRatioSelect'),
  quickEditApplyCropBtn: document.getElementById('quickEditApplyCropBtn'),
  quickEditCancelCropBtn: document.getElementById('quickEditCancelCropBtn'),
  cropSubOptions: document.getElementById('cropSubOptions'),
  quickEditRotateLeftBtn: document.getElementById('quickEditRotateLeftBtn'),
  quickEditRotateRightBtn: document.getElementById('quickEditRotateRightBtn'),
  quickEditCropBtn: document.getElementById('quickEditCropBtn'),
  quickEditSmartFixBtn: document.getElementById('quickEditSmartFixBtn'),
  smartFixSubOptions: document.getElementById('smartFixSubOptions'),
  smartFixIntensitySlider: document.getElementById('smartFixIntensitySlider'),
  smartFixIntensityVal: document.getElementById('smartFixIntensityVal'),
  quickEditCompareBtn: document.getElementById('quickEditCompareBtn'),
  quickEditResetBtn: document.getElementById('quickEditResetBtn'),
  quickEditCancelBtn: document.getElementById('quickEditCancelBtn'),
  quickEditSaveBtn: document.getElementById('quickEditSaveBtn'),
  quickEditSaveCopyBtn: document.getElementById('quickEditSaveCopyBtn'),
  importModal: document.getElementById('importModal'),
  importBackdrop: document.getElementById('importBackdrop'),
  closeImportModalBtn: document.getElementById('closeImportModalBtn'),
  cancelImportBtn: document.getElementById('cancelImportBtn'),
  startImportBtn: document.getElementById('startImportBtn'),
  importPathInput: document.getElementById('importPathInput'),
  importRecursiveCheck: document.getElementById('importRecursiveCheck'),
  importProgressBox: document.getElementById('importProgressBox'),
  importProgressBar: document.getElementById('importProgressBar'),
  importStatusCounts: document.getElementById('importStatusCounts'),
  importCurrentFile: document.getElementById('importCurrentFile'),
  newAlbumModal: document.getElementById('newAlbumModal'),
  newAlbumBackdrop: document.getElementById('newAlbumBackdrop'),
  closeNewAlbumModalBtn: document.getElementById('closeNewAlbumModalBtn'),
  cancelAlbumBtn: document.getElementById('cancelAlbumBtn'),
  createAlbumSubmitBtn: document.getElementById('createAlbumSubmitBtn'),
  albumNameInput: document.getElementById('albumNameInput'),
  albumDescInput: document.getElementById('albumDescInput'),
  addToAlbumModal: document.getElementById('addToAlbumModal'),
  addToAlbumBackdrop: document.getElementById('addToAlbumBackdrop'),
  closeAddToAlbumModalBtn: document.getElementById('closeAddToAlbumModalBtn'),
  cancelAddToAlbumBtn: document.getElementById('cancelAddToAlbumBtn'),
  confirmAddToAlbumBtn: document.getElementById('confirmAddToAlbumBtn'),
  addToAlbumSelect: document.getElementById('addToAlbumSelect'),
  addToAlbumSelectGroup: document.getElementById('addToAlbumSelectGroup'),
  addToAlbumTargetCount: document.getElementById('addToAlbumTargetCount'),
  noAlbumsNotice: document.getElementById('noAlbumsNotice'),
  newTagModal: document.getElementById('newTagModal'),
  newTagBackdrop: document.getElementById('newTagBackdrop'),
  closeNewTagModalBtn: document.getElementById('closeNewTagModalBtn'),
  cancelTagBtn: document.getElementById('cancelTagBtn'),
  createTagSubmitBtn: document.getElementById('createTagSubmitBtn'),
  tagNameInput: document.getElementById('tagNameInput'),
  tagCategorySelect: document.getElementById('tagCategorySelect'),
  tagModalHeading: document.getElementById('tagModalHeading'),
  tagModalPhotoTarget: document.getElementById('tagModalPhotoTarget'),
  tagModalPhotoThumb: document.getElementById('tagModalPhotoThumb'),
  tagModalPhotoCountBadge: document.getElementById('tagModalPhotoCountBadge'),
  tagModalPhotoName: document.getElementById('tagModalPhotoName'),
  tagModalPhotoMeta: document.getElementById('tagModalPhotoMeta'),
  tagModalPhotoTagsRow: document.getElementById('tagModalPhotoTagsRow'),
  tagModalPhotoCurrentTags: document.getElementById('tagModalPhotoCurrentTags'),
  tagModalApplyGroup: document.getElementById('tagModalApplyGroup'),
  tagModalApplyToPhotoCheckbox: document.getElementById('tagModalApplyToPhotoCheckbox'),
  tagModalApplyLabel: document.getElementById('tagModalApplyLabel'),
  tagDetectedBadge: document.getElementById('tagDetectedBadge'),
  tagModalSuggestions: document.getElementById('tagModalSuggestions'),
  tagModalClearInputBtn: document.getElementById('tagModalClearInputBtn'),
  tagCategoryCards: document.getElementById('tagCategoryCards'),
  tagSearchHelpTitle: document.getElementById('tagSearchHelpTitle'),
  tagSearchHelpSub: document.getElementById('tagSearchHelpSub'),
  tagSearchHelpChips: document.getElementById('tagSearchHelpChips'),
  inspectorAddTagModalBtn: document.getElementById('inspectorAddTagModalBtn'),
  inspectorOpenTagModalBtn: document.getElementById('inspectorOpenTagModalBtn'),
  deleteMediaModal: document.getElementById('deleteMediaModal'),
  deleteMediaBackdrop: document.getElementById('deleteMediaBackdrop'),
  closeDeleteMediaModalBtn: document.getElementById('closeDeleteMediaModalBtn'),
  cancelDeleteMediaBtn: document.getElementById('cancelDeleteMediaBtn'),
  confirmDeleteMediaBtn: document.getElementById('confirmDeleteMediaBtn'),
  deleteMediaPromptText: document.getElementById('deleteMediaPromptText'),
  deleteFromDiskCheckbox: document.getElementById('deleteFromDiskCheckbox'),
  deleteMediaWarningText: document.getElementById('deleteMediaWarningText'),
  deleteTagModal: document.getElementById('deleteTagModal'),
  deleteTagBackdrop: document.getElementById('deleteTagBackdrop'),
  closeDeleteTagModalBtn: document.getElementById('closeDeleteTagModalBtn'),
  cancelDeleteTagBtn: document.getElementById('cancelDeleteTagBtn'),
  confirmDeleteTagBtn: document.getElementById('confirmDeleteTagBtn'),
  deleteTagPromptText: document.getElementById('deleteTagPromptText'),
  deleteTagWarningText: document.getElementById('deleteTagWarningText'),
  batchDateModal: document.getElementById('batchDateModal'),
  batchDateBackdrop: document.getElementById('batchDateBackdrop'),
  closeBatchDateModalBtn: document.getElementById('closeBatchDateModalBtn'),
  cancelBatchDateBtn: document.getElementById('cancelBatchDateBtn'),
  confirmBatchDateBtn: document.getElementById('confirmBatchDateBtn'),
  batchDateTargetCount: document.getElementById('batchDateTargetCount'),
  batchDateRefInfo: document.getElementById('batchDateRefInfo'),
  batchDateRefName: document.getElementById('batchDateRefName'),
  batchDateRefOriginal: document.getElementById('batchDateRefOriginal'),
  batchDateInput: document.getElementById('batchDateInput'),
  batchDateShiftHours: document.getElementById('batchDateShiftHours'),
  shiftMinus24Btn: document.getElementById('shiftMinus24Btn'),
  shiftMinus1Btn: document.getElementById('shiftMinus1Btn'),
  shiftPlus1Btn: document.getElementById('shiftPlus1Btn'),
  shiftPlus24Btn: document.getElementById('shiftPlus24Btn'),
  batchDateTimezoneSelect: document.getElementById('batchDateTimezoneSelect'),
  batchDateTzFrom: document.getElementById('batchDateTzFrom'),
  batchDateTzTo: document.getElementById('batchDateTzTo'),
  batchDateModeShift: document.getElementById('batchDateModeShift'),
  batchDateModeExact: document.getElementById('batchDateModeExact'),
  batchDatePreview: document.getElementById('batchDatePreview'),
  batchMoveModal: document.getElementById('batchMoveModal'),
  batchMoveBackdrop: document.getElementById('batchMoveBackdrop'),
  closeBatchMoveModalBtn: document.getElementById('closeBatchMoveModalBtn'),
  cancelBatchMoveBtn: document.getElementById('cancelBatchMoveBtn'),
  confirmBatchMoveBtn: document.getElementById('confirmBatchMoveBtn'),
  batchMoveModalTitle: document.getElementById('batchMoveModalTitle'),
  batchMoveTargetCount: document.getElementById('batchMoveTargetCount'),
  batchMovePathInput: document.getElementById('batchMovePathInput'),
  batchMoveFolderSuggestions: document.getElementById('batchMoveFolderSuggestions')
};

export function refreshDomReferences() {
  for (const key in dom) {
    if (!dom[key]) {
      dom[key] = document.getElementById(key);
    }
  }
  if (!dom.mapSearchBox) {
    dom.mapSearchBox = document.querySelector('.map-search-box');
  }
}

export function validateRequiredDom() {
  refreshDomReferences();
  const requiredDom = [
    'mediaGrid',
    'emptyState',
    'viewTabs',
    'navAllMedia',
    'navPicks',
    'navRejects',
    'navNotRejects',
    'navUnrated'
  ];

  const missing = requiredDom.filter(name => !dom[name]);
  if (missing.length > 0) {
    throw new Error(`Missing required DOM elements: ${missing.join(', ')}`);
  }
}

export function showToast(message, type = 'info') {
  let container = document.getElementById('toastContainer');
  if (!container) {
    container = document.createElement('div');
    container.id = 'toastContainer';
    container.style.cssText = 'position:fixed;bottom:24px;left:50%;transform:translateX(-50%);z-index:9999;display:flex;flex-direction:column;gap:8px;pointer-events:none;';
    document.body.appendChild(container);
  }
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  toast.style.cssText = 'background:rgba(30,30,30,0.95);color:#fff;padding:8px 16px;border-radius:6px;font-size:13px;box-shadow:0 4px 12px rgba(0,0,0,0.3);pointer-events:auto;border-left:4px solid ' + (type === 'error' ? '#e74c3c' : '#3498db');
  toast.textContent = message;
  container.appendChild(toast);
  setTimeout(() => {
    toast.style.transition = 'opacity 0.3s';
    toast.style.opacity = '0';
    setTimeout(() => toast.remove(), 300);
  }, 4000);
}
